import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import type { Exercise } from '../../src/types/exercise';

const projectRoot = resolve(__dirname, '../..');

export const EXERCISE_MANIFEST_PATH = resolve(
  projectRoot,
  'src/constants/exerciseAssetManifest.ts',
);

export function writeExerciseAssetManifest(
  exercises: Exercise[],
  generatedBy = 'scripts/lib/exerciseManifest.ts',
): void {
  const resolveRequire = (uri: string) => {
    const relative = uri.replace(/^assets\//, '../../assets/');
    return `require('${relative}')`;
  };

  const thumbnailLines = exercises.map(
    (exercise) => `  '${exercise.id}': ${resolveRequire(exercise.thumbnailUri)},`,
  );
  const gifLines = exercises.map(
    (exercise) => `  '${exercise.id}': ${resolveRequire(exercise.gifUri)},`,
  );

  const content = `// AUTO-GENERATED by ${generatedBy} — do not edit manually.
import type { ImageSourcePropType } from 'react-native';

export const EXERCISE_THUMBNAIL_MANIFEST: Record<string, ImageSourcePropType> = {
${thumbnailLines.join('\n')}
};

export const EXERCISE_GIF_MANIFEST: Record<string, ImageSourcePropType> = {
${gifLines.join('\n')}
};
`;

  writeFileSync(EXERCISE_MANIFEST_PATH, content, 'utf8');
}
