import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { execSync } from 'node:child_process';

import { isBodyPartLikeName } from './lib/exerciseQualityRules';
import {
  EXERCISE_LIBRARY_SOURCE,
  TARGET_LIBRARY_MAX,
  TARGET_LIBRARY_MIN,
  type FreeExerciseDbRecord,
  selectExercises,
  transformToTuneExercise,
} from './lib/freeExerciseDbTransform';

const projectRoot = resolve(__dirname, '..');
const vendorPath = resolve(projectRoot, '.vendor/free-exercise-db');
const sourcePath = process.env.FREE_EXERCISE_DB_PATH ?? vendorPath;
const seedPath = resolve(projectRoot, 'assets/seed/exercises.json');
const thumbnailDir = resolve(projectRoot, 'assets/exercises/thumbnails');
const gifDir = resolve(projectRoot, 'assets/exercises/gifs');
const placeholderDir = resolve(projectRoot, 'assets/exercises/placeholders');
const manifestPath = resolve(projectRoot, 'src/constants/exerciseAssetManifest.ts');
const reportPath = resolve(projectRoot, 'scripts/reports/exercise-import-report.json');

function ensureSourceRepo(): void {
  if (existsSync(join(sourcePath, 'dist/exercises.json'))) {
    return;
  }

  mkdirSync(resolve(projectRoot, '.vendor'), { recursive: true });
  if (existsSync(vendorPath)) {
    rmSync(vendorPath, { recursive: true, force: true });
  }

  console.log('Cloning free-exercise-db into .vendor/free-exercise-db ...');
  execSync(`git clone --depth 1 https://github.com/yuhonas/free-exercise-db.git "${vendorPath}"`, {
    stdio: 'inherit',
  });
}

function copyImage(sourceRelative: string, destination: string): boolean {
  const sourceFile = join(sourcePath, 'exercises', sourceRelative);
  if (!existsSync(sourceFile)) {
    return false;
  }
  copyFileSync(sourceFile, destination);
  return true;
}

function writeManifest(exercises: ReturnType<typeof transformToTuneExercise>[]): void {
  const thumbnailLines = exercises.map(
    (exercise) => `  '${exercise.id}': require('../../assets/exercises/thumbnails/${exercise.id}.jpg'),`,
  );
  const gifLines = exercises.map(
    (exercise) => `  '${exercise.id}': require('../../assets/exercises/gifs/${exercise.id}.jpg'),`,
  );

  const content = `// AUTO-GENERATED by scripts/import-free-exercise-db.ts — do not edit manually.
import type { ImageSourcePropType } from 'react-native';

export const EXERCISE_THUMBNAIL_MANIFEST: Record<string, ImageSourcePropType> = {
${thumbnailLines.join('\n')}
};

export const EXERCISE_GIF_MANIFEST: Record<string, ImageSourcePropType> = {
${gifLines.join('\n')}
};
`;

  writeFileSync(manifestPath, content, 'utf8');
}

function main(): void {
  ensureSourceRepo();

  const raw = readFileSync(join(sourcePath, 'dist/exercises.json'), 'utf8');
  const records = JSON.parse(raw) as FreeExerciseDbRecord[];

  const { selected, removed } = selectExercises(records, 160);

  if (selected.length < TARGET_LIBRARY_MIN || selected.length > TARGET_LIBRARY_MAX) {
    throw new Error(
      `Selected ${selected.length} exercises; expected ${TARGET_LIBRARY_MIN}-${TARGET_LIBRARY_MAX}.`,
    );
  }

  rmSync(thumbnailDir, { recursive: true, force: true });
  rmSync(gifDir, { recursive: true, force: true });
  mkdirSync(thumbnailDir, { recursive: true });
  mkdirSync(gifDir, { recursive: true });
  mkdirSync(placeholderDir, { recursive: true });

  const muscleFixes: Array<{ id: string; name: string; muscleGroup: string }> = [];

  const exercises = selected.map((record) => {
    const thumbnailUri = `assets/exercises/thumbnails/${record.id}.jpg`;
    const gifUri = `assets/exercises/gifs/${record.id}.jpg`;
    const thumbSource = record.images[0];
    const gifSource = record.images[1] ?? record.images[0];

    const thumbCopied = copyImage(thumbSource, join(thumbnailDir, `${record.id}.jpg`));
    const gifCopied = copyImage(gifSource, join(gifDir, `${record.id}.jpg`));

    if (!thumbCopied || !gifCopied) {
      throw new Error(`Missing media for ${record.id}`);
    }

    const exercise = transformToTuneExercise(record, thumbnailUri, gifUri);

    if (record.id === 'Crossover_Reverse_Lunge' || record.id === 'Frog_Hops') {
      muscleFixes.push({ id: exercise.id, name: exercise.name, muscleGroup: exercise.muscleGroup });
    }

    return exercise;
  });

  writeFileSync(seedPath, `${JSON.stringify(exercises, null, 2)}\n`, 'utf8');
  writeManifest(exercises);

  const byDifficulty: Record<string, number> = {};
  const byMuscleGroup: Record<string, number> = {};
  const byEquipment: Record<string, number> = {};
  const byCategory: Record<string, number> = {};
  const bySessionRole: Record<string, number> = {};
  const removedByReason: Record<string, number> = {};

  for (const exercise of exercises) {
    byDifficulty[exercise.difficulty] = (byDifficulty[exercise.difficulty] ?? 0) + 1;
    byMuscleGroup[exercise.muscleGroup] = (byMuscleGroup[exercise.muscleGroup] ?? 0) + 1;
    byEquipment[exercise.equipment] = (byEquipment[exercise.equipment] ?? 0) + 1;
    bySessionRole[exercise.sessionRole] = (bySessionRole[exercise.sessionRole] ?? 0) + 1;
    for (const category of exercise.categories) {
      byCategory[category] = (byCategory[category] ?? 0) + 1;
    }
  }

  for (const item of removed) {
    removedByReason[item.reason] = (removedByReason[item.reason] ?? 0) + 1;
  }

  const bodyPartInLibrary = exercises.filter((e) => isBodyPartLikeName(e.name));

  const report = {
    importedAt: new Date().toISOString(),
    source: 'https://github.com/yuhonas/free-exercise-db',
    sourcePath,
    sourceRecordCount: records.length,
    removedCount: removed.length,
    removedByReason,
    removedExamples: removed.slice(0, 25),
    exerciseCount: exercises.length,
    thumbnailCount: exercises.length,
    detailFrameCount: exercises.length,
    thumbnailCoveragePercent: 100,
    detailFrameCoveragePercent: 100,
    bodyPartEntriesRemaining: bodyPartInLibrary.length,
    muscleFixExamples: muscleFixes,
    sourceField: EXERCISE_LIBRARY_SOURCE,
    byDifficulty,
    byMuscleGroup,
    byEquipment,
    byCategory,
    bySessionRole,
  };

  mkdirSync(resolve(projectRoot, 'scripts/reports'), { recursive: true });
  writeFileSync(reportPath, `${JSON.stringify(report, null, 2)}\n`, 'utf8');

  console.log(`Removed ${removed.length} disqualified records.`);
  console.log(`Imported ${exercises.length} exercises.`);
  console.log(`Thumbnail coverage: ${exercises.length}/${exercises.length}`);
  console.log(`Detail frame coverage: ${exercises.length}/${exercises.length}`);
  console.log('Muscle fixes:', muscleFixes);
  console.log(`Report: ${reportPath}`);
}

main();
